id: I8FF18F37
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T14:30:29+00:00'
last_modified: '2022-06-15T15:23:35.280768+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03818
  title: བསྟན་པ་བོན་གྱི་ཀླད་དོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DAA1:
      image_group_id: I2KG200138
      title: Volume 1 of bstan pa bon gyi klad don/
      total_pages: 99
      order: 1
      base_file: DAA1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
