id: P000310
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:19.591592
source_metadata:
  id: bdr:W00KG03818
  title: བསྟན་པ་བོན་གྱི་ཀླད་དོན།
  author: ''
  volumes:
    f6a6113ddc1740f4832a0126d19f08ad:
      image_group_id: I2KG200138
      title: Volume 1 of bstan pa bon gyi klad don/
      volume_number: 1
      total_pages: 99
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
